### ISSUE TITLE
Wrong dependences

### ISSUE THREAD

**Issue by x11tete11x** [gaboelnuevo/mylaunchpad#4]
there is some mistake in github instructions says:

Dependences: python-gmenu pygtk pyhton-lxml python-cairo python-imaging

and should be (python-lxml it's wrong writed):

Dependences: python-gmenu pygtk python-lxml python-cairo python-imaging

and i also need to install: python-distutils-extra

thx!

**Comment by gaboelnuevo** [comment]
Thanks. This is fixed now
