### ISSUE TITLE
Can I run it on Ubuntu 14.04?

### ISSUE THREAD

**Issue by kensully** [gaboelnuevo/mylaunchpad#5]
Hi
Thank you for sharing your project. I like it since it's lightweight and fast. 
I'd like to run it on my Ubuntu but it's not compatible.
I wish you port it to run in Ubuntu.
Regards.
Kenn

**Comment by gaboelnuevo** [comment]
Hi Ken have you tried to run it in ubuntu 14.04? Do you get any error?
Try to clone repository and run "python setup.py install" inside the directory and try to resolve dependences. I think it should work if you get all dependences.

**Comment by kensully** [comment]
I installed it and ran. It opens but it exceeds boundaries of the screen. I think it fails to detect screen size.

**Comment by gaboelnuevo** [comment]
Can you take any screenshot?

**Comment by kensully** [comment]
here http://oi61.tinypic.com/k1dyx5.jpg

**Comment by gaboelnuevo** [comment]
hello thanks for your feedback!
I think that can be a bug because are so many categories in the xdg-menu (I will try to fix it when I have time... )
 You could try change xdg-menu option in config file for another to test it if you want.

**Comment by kensully** [comment]
Thank you for your help. Terminal output might give you more clue:

       ~$ mylaunchpad
      Hidden imported:  set([])
      Favorites imported:  set([])
      Compositing True
      /etc/xdg/menus/applications.menu Not found!
      Favorites exported
      Hidden exported
Have a good time.

**Comment by gaboelnuevo** [comment]
Do you have applications.menu in your /etc/xdg/menus directory?
What is the output of ls /etc/xdg/menus?

**Comment by kensully** [comment]
it's 

     applications-gnome-merged        gnomecc.menu                       unitycc.menu
     applications-merged              gnome-flashback-applications.menu  unity-lens-applications.menu
     classicmenuindicatorsystem.menu  kde4-applications.menu             xfce-applications.menu
     debian-menu.menu                 lxde-applications.menu
     gnome-applications.menu          lxlauncher-applications.menu

**Comment by gaboelnuevo** [comment]
You don't have applications.menu in your /etc/xdg/menus 

Try launch in your terminal:
$ mylaunchpad gnome-applications
Or another menu file name: like lxde-applications, kde4-applications, etc

**Comment by kensully** [comment]
$ mylaunchpad gnome-applications 
is the same as in the picture I sent.
But this one works though it doesn't list all the applications in `/usr/share/applications` directory.
Anyway, I can handle the rest.
I'm grateful to you man.
Thank you.
All the best.

**Comment by gaboelnuevo** [comment]
you're welcome!

**Comment by LoranKey** [comment]
Very useful !!!
Works very well on Manjaro Openbox. Light and fast.
I just add this to my ~/.config/openbox/rc.xml

```
    <keybind key="W-space">
      <action name="Execute">
        <startupnotify>
          <enabled>true</enabled>
          <name>MyLaunchpad</name>
        </startupnotify>
        <command>mylaunchpad kde-applications</command>
      </action>
    </keybind>
```

Do you plan to add a panel controller ? A tint2 killer :)

Many thanks !

**Comment by gaboelnuevo** [comment]
Thanks u! No I don't have this plan but it would be nice... I don´t have time at this moment and I think that would be great to find maintainers.

**Comment by LoranKey** [comment]
Hi,
I did some improvements : http://www.mediafire.com/download/lpao2x6bd5ohzup/mylaunchpad_propal_0.4.tar.gz

- internationalization (only French translation at the moment)
- settings are now located in ~/.mylaunchpad/conf
- we can change display settings in this file

Best regards

**Comment by gaboelnuevo** [comment]
Thanks a lot! I'll review your contribution as soon as possible.

**Comment by kensully** [comment]
I have hundreds of apps installed and categories toolbar doesn't fit in screen because there are lots of categories and category  titles are not truncated. I can not figure out how to truncate names of categories.
Would anybody help me with it?

**Comment by gaboelnuevo** [comment]
I need to fix this, for now this branch can be an option: https://github.com/gaboelnuevo/mylaunchpad/tree/category-icons
