### ISSUE TITLE
mylaunchpad won't launch

### ISSUE THREAD

**Issue by klundry** [gaboelnuevo/mylaunchpad#7]
When I try to launch I get the following output.

[kellen@alarm-flip menus]$ mylaunchpad lxqt-applications     
Hidden imported:  set([])
Favorites imported:  set([])
Compositing False
Traceback (most recent call last):
  File "/usr/bin/mylaunchpad", line 858, in <module>
    launcher = MyLauncher()
  File "/usr/bin/mylaunchpad", line 705, in __init__
    self.init_window()
  File "/usr/bin/mylaunchpad", line 810, in init_window
    apps = AppStore(mainbox, self)
  File "/usr/bin/mylaunchpad", line 217, in __init__
    self.load("ALL")
  File "/usr/bin/mylaunchpad", line 275, in load
    self.fill_buttonsContainer(apps)   
  File "/usr/bin/mylaunchpad", line 467, in fill_buttonsContainer
    self.add_button(item, row_widget)
  File "/usr/bin/mylaunchpad", line 489, in add_button
    icon = self.get_icon(icon_name)
  File "/usr/bin/mylaunchpad", line 411, in get_icon
    pixbuf = theme.load_icon("exec",size, 0)
glib.GError: Icon 'exec' not present in theme

**Comment by gaboelnuevo** [comment]
the icon "exec" doesn't exists in the default lxqt icon theme.
you can install a new icon pack like oxygen-icon-theme another option y change "exec" in the line
pixbuf = theme.load_icon("exec",size, 0) with your favorite icon

**Comment by klundry** [comment]
I'm using arch and have the oxygen-icons package installed already.  I wasn't using it, but I switched to it just to see if it would launch but I still get the same error.

**Comment by klundry** [comment]
I went ahead and changed exec to something else and now I get this.

[kellen@alarm-flip ~]$ mylaunchpad 
Hidden imported:  set([])
Favorites imported:  set([])
Compositing False
Traceback (most recent call last):
  File "/usr/bin/mylaunchpad", line 858, in <module>
    launcher = MyLauncher()
  File "/usr/bin/mylaunchpad", line 705, in __init__
    self.init_window()
  File "/usr/bin/mylaunchpad", line 822, in init_window
    pilimg = Image.fromstring("RGB", wh, pb.get_pixels())
  File "/usr/lib/python2.7/site-packages/PIL/Image.py", line 2053, in fromstring
    "Please call frombytes() instead.")
Exception: fromstring() has been removed. Please call frombytes() instead.

**Comment by gaboelnuevo** [comment]
PIL library was updated and now fromstring method is deprecated we need to use frombytes() instead, I´ll try to fix it when i had time. if someone else can fix this now please do it

**Comment by gaboelnuevo** [comment]
I think that problem was resolved in latest commits, I forgot to close the issue a few months ago if the problem persists try to install a composite manager (like xcompmgr or compton) or open a new issue.

Att. Gabriel SL.

**Comment by kjyv** [comment]
I had to install gnome-icon-theme, compton or oxygen or tango didn't help.

**Comment by gaboelnuevo** [comment]
@kjyv you need to install compton but you need to run it too. make sure that you're already running compton first then launch mylaunchpad. Try it or open a new issue please.

**Comment by kjyv** [comment]
Also tried that, didn't help. The error message states that it can't find the icon 'exec' probably because it was not installed. It is part of gnome-icon-theme (debian package). Not sure why a compositor would help
